GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Jamie Balba",
    "number": "111-111-1111"
}

###
GET http://localhost:3001/api/persons/3

### 
DELETE  http://localhost:3001/api/persons/3
