
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "testUser",
    "name": "testUser",
    "password": "password"
}

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "Jamie",
    "name": "Jamie",
    "password": "password"
}

### 
GET http://localhost:3001/api/users/